### ISSUE TITLE
PyViz Workshop Notes 11-16-2021

### ISSUE THREAD

**Issue by kjhogue** [juanshishido/visualization-with-python#10]
7 participants at start of workshop.  Feedback link wasn't working, so checked in with front desk/Aaron/Sev for help. Total of 9 participants at 1:45 pm. 8 as of 2:50 pm. Everything going well in workshop. 9 as of 3:39 pm.

- Typo in this line here just above scatterplot section: "Does Spain or Portugal have a higher life expectantcy across all the years? How does this relate to per-capita GDP? How might we look for a relationship? - expectancy is spelled wrong. 
- Typo in this line here: "That looks much better. We can now see there is somehwhat of a linear relationship between the log of GDP and life expectancy. Interesting!" -somewhat is spelled wrong. It's just above the section on Transparency. 
- Also, the section head for the Transformations section needs correction - it reads: "Transormations". 
- In the section on Color - typo = "plt.ylabel('Life Expectency (Years)');" s/b "Expectancy"?  @pssachdeva @bypdlab -add anything I might have missed

**Comment by pssachdeva** [comment]
Closed by #11.
