### ISSUE TITLE
Typos for 'expectancy' in challenge questions for histograms section and scatter plots section

### ISSUE THREAD

**Issue by stemlock** [juanshishido/visualization-with-python#5]
There are a few typos across the notebook for 'expectancy'. 

Fix the challenge questions in the histogram section to:

1. Create a histogram of life expectancy in the year 2007 across all 142 countries in the gapminder dataset. Play with the `bins=` parameter to find the most informative bin number.

2. What can you say about the distribution of life expectancy values in 2007?

Also fix the text in the plots of the scatter plot section.

**Comment by pssachdeva** [comment]
Closed by #11.
