### ISSUE TITLE
Simplifying plot code in Bar Plot section

### ISSUE THREAD

**Issue by stemlock** [juanshishido/visualization-with-python#6]
Currently, we are creating a lot of new variables in order to create a simple bar plot. Some of which are not even used, such as the `x` variable for ticks.

Instead, we could simplify the plot calls by using the `country_counts` dataframe columns directly.

**Matplotlib plot call**
plt.bar(country_counts['continent'], country_counts['n_countries']);

**Pandas plot call**
country_counts.plot(kind='bar', x='continent', y='n_countries', legend=False);

**Comment by pssachdeva** [comment]
Closed by #11.
