### ISSUE TITLE
Title, xlabel, ylabel commands in the pandas hist function

### ISSUE THREAD

**Issue by bypdlab** [juanshishido/visualization-with-python#8]
Pratik suggested a great edit/addition for the title, xlabel, ylabel commands in the pandas hist function under the 'Pandas methods to make plots' section:

gm_latest.hist(column='gdpPercap', bins=3)
plt.title('Distribution of Global Per-Capita GDP in 2007')
plt.xlabel('Per-Capita GDP (Millions of USD)')
plt.ylabel('# of Countries')

**Comment by pssachdeva** [comment]
Closed by #11.
