### ISSUE TITLE
Line Plot Challenge

### ISSUE THREAD

**Issue by bypdlab** [juanshishido/visualization-with-python#9]
The challenge for the Line Plot section gives the same plot as the example that we use above, so we might want to try something different.

To get started, Pratik suggested we show more customizations (e.g., font size, etc.):

plt.figure(figsize=(10,5))
plt.plot(spain['year'], spain['lifeExp'], label='Spain')
plt.plot(portugal['year'], portugal['lifeExp'], label='Portugal')
plt.title('Life Expectantcy of Portugal & Spain', fontsize=18)
plt.xlabel('Time (Years)', fontsize=15)
plt.ylabel('Life Expectantcy (Years)', fontsize=15)
plt.legend(prop={'size': 13});

**Comment by pssachdeva** [comment]
Closed by #11.
